debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.surup.websocket_chat: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/websocket_chat
    username: jhm7509
    password: ThisIsTestPassword#@!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: true
  sql.init.mode: always

---

#spring:
#  config.activate.on-profile: test
#  datasource:
#    url: jdbc:h2:mem:websocket_chat;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none
