debug: false
management.endpoints.web.exposure.include: "*" # production: (actuator) remove or spring security config

logging:
  level:
    com.surup.websocket_chat: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/websocket_chat
    username: jhm7509
    password: ThisIsTestPassword#@!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # data sql
    hibernate.ddl-auto: create # production: set none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    open-in-view: false # return connection before response
  sql.init.mode: always # data sql: always(service), embedded(embedded db), none
  h2.console.enabled: false
  thymeleaf.cache: false # production: auto remove
#  thymeleaf3.decoupled-logic: true

# spring security
#spring.security.user.name: id1
#spring.security.user.password: ThisIsPassword
